import { tiers, type TierPrice, type CatalogItem } from "./catalogTypes";

export type AutoPartCategory = "engine" | "brakes-suspension" | "electrical-lighting";

export interface AutoPart extends CatalogItem {
  category: AutoPartCategory;
  sku: string;
  basePrice: number;
  moq: number;
  /** Bulk packaging option, e.g. "Single", "Pack of 4" — plays the role "sizes" plays for apparel. */
  packSizes: string[];
  /** Part grade/sourcing, e.g. "OEM", "Aftermarket" — plays the role "colors" plays for apparel. */
  grades: string[];
  tag?: "New" | "Bestseller" | "Low stock" | "Restocked";
  image: string;
}

export const autoPartCategories: { id: AutoPartCategory; label: string; description: string }[] = [
  { id: "engine", label: "Engine & filters", description: "Filters, belts, plugs & fluids" },
  { id: "brakes-suspension", label: "Brakes & suspension", description: "Pads, discs, shocks & bushings" },
  { id: "electrical-lighting", label: "Electrical & lighting", description: "Batteries, bulbs & sensors" },
];

export const autoParts: AutoPart[] = [
  {
    id: "ap1",
    slug: "oil-filter-standard",
    image: "/product/images/oil-filter-standard.jpg",
    name: "Oil Filter, Standard Spin-On",
    category: "engine",
    sku: "ENG-OFL-001",
    basePrice: 450,
    tierPricing: tiers(450),
    moq: 24,
    packSizes: ["Single", "Pack of 12", "Case of 48"],
    grades: ["OEM", "Aftermarket"],
    description: "Fits most 1.4L–2.0L petrol/diesel engines. Anti-drain-back valve, filters down to 20 microns.",
    tag: "Bestseller",
  },
  {
    id: "ap2",
    slug: "timing-belt-kit",
    image: "/product/images/timing-belt-kit.jpg",
    name: "Timing Belt Kit + Tensioner",
    category: "engine",
    sku: "ENG-TBK-014",
    basePrice: 6200,
    tierPricing: tiers(6200),
    moq: 6,
    packSizes: ["Single kit"],
    grades: ["OEM", "Premium Aftermarket"],
    description: "Complete kit: belt, tensioner pulley, idler pulley. Covers common 1.6L–2.2L applications.",
  },
  {
    id: "ap3",
    slug: "spark-plug-iridium",
    image: "/product/images/spark-plug-iridium.jpg",
    name: "Spark Plug, Iridium",
    category: "engine",
    sku: "ENG-SPK-022",
    basePrice: 380,
    tierPricing: tiers(380),
    moq: 48,
    packSizes: ["Single", "Set of 4", "Case of 100"],
    grades: ["OEM", "Aftermarket"],
    description: "Fine-wire iridium tip for longer service life and stable ignition. Pre-gapped, ready to install.",
    tag: "Restocked",
  },
  {
    id: "ap4",
    slug: "engine-oil-5w30",
    image: "/product/images/engine-oil-5w30.jpg",
    name: "Engine Oil 5W-30, Synthetic",
    category: "engine",
    sku: "ENG-OIL-009",
    basePrice: 2100,
    tierPricing: tiers(2100),
    moq: 12,
    packSizes: ["4L jug", "Case of 4 (4L)", "Drum (208L)"],
    grades: ["Fully Synthetic", "Semi-Synthetic"],
    description: "API SN/CF fully synthetic oil, suits most modern petrol/diesel engines under warranty spec.",
  },
  {
    id: "ap5",
    slug: "air-filter-panel",
    image: "/product/images/air-filter-panel.jpg",
    name: "Air Filter, Panel",
    category: "engine",
    sku: "ENG-AIR-031",
    basePrice: 520,
    tierPricing: tiers(520),
    moq: 24,
    packSizes: ["Single", "Pack of 10"],
    grades: ["OEM", "Aftermarket"],
    description: "Pleated paper element, direct-fit replacement. High dust-holding capacity for local road conditions.",
  },
  {
    id: "ap6",
    slug: "fan-belt-serpentine",
    image: "/product/images/fan-belt-serpentine.jpg",
    name: "Serpentine Fan Belt",
    category: "engine",
    sku: "ENG-BLT-018",
    basePrice: 980,
    tierPricing: tiers(980),
    moq: 12,
    packSizes: ["Single"],
    grades: ["OEM", "Aftermarket"],
    description: "EPDM rubber construction, resists heat cracking. Common ribbed profile across several makes.",
    tag: "New",
  },
  {
    id: "ap7",
    slug: "brake-pads-front",
    image: "/product/images/brake-pads-front.jpg",
    name: "Brake Pads, Front Set",
    category: "brakes-suspension",
    sku: "BRK-PAD-041",
    basePrice: 1800,
    tierPricing: tiers(1800),
    moq: 12,
    packSizes: ["Set (4 pads)", "Case of 10 sets"],
    grades: ["OEM", "Ceramic", "Semi-Metallic"],
    description: "Low-dust ceramic compound, includes wear sensor and hardware kit. Bedded-in surface finish.",
    tag: "Bestseller",
  },
  {
    id: "ap8",
    slug: "brake-discs-pair",
    image: "/product/images/brake-discs-pair.jpg",
    name: "Brake Discs, Front Pair",
    category: "brakes-suspension",
    sku: "BRK-DSC-007",
    basePrice: 3400,
    tierPricing: tiers(3400),
    moq: 6,
    packSizes: ["Pair", "Case of 6 pairs"],
    grades: ["OEM", "Vented Aftermarket"],
    description: "Vented and coated for corrosion resistance. Balanced and machined to OE tolerance.",
  },
  {
    id: "ap9",
    slug: "shock-absorber-front",
    image: "/product/images/shock-absorber-front.jpg",
    name: "Shock Absorber, Front",
    category: "brakes-suspension",
    sku: "BRK-SHK-055",
    basePrice: 2600,
    tierPricing: tiers(2600),
    moq: 6,
    packSizes: ["Single", "Pair"],
    grades: ["OEM", "Gas-Charged Aftermarket"],
    description: "Twin-tube gas-charged design for consistent damping across rough road conditions.",
    tag: "Bestseller",
  },
  {
    id: "ap10",
    slug: "control-arm-bushing",
    image: "/product/images/control-arm-bushing.jpg",
    name: "Control Arm Bushing Set",
    category: "brakes-suspension",
    sku: "BRK-BSH-063",
    basePrice: 950,
    tierPricing: tiers(950),
    moq: 12,
    packSizes: ["Set", "Case of 10 sets"],
    grades: ["OEM Rubber", "Reinforced Polyurethane"],
    description: "Reduces play and clunking over bumps. Direct bolt-in replacement, no modification needed.",
  },
  {
    id: "ap11",
    slug: "wheel-bearing-hub",
    image: "/product/images/wheel-bearing-hub.jpg",
    name: "Wheel Bearing & Hub Assembly",
    category: "brakes-suspension",
    sku: "BRK-HUB-028",
    basePrice: 4100,
    tierPricing: tiers(4100),
    moq: 4,
    packSizes: ["Single"],
    grades: ["OEM", "Aftermarket"],
    description: "Pre-assembled unit with sealed bearing and ABS sensor ring where applicable. Bolt-on install.",
    tag: "New",
  },
  {
    id: "ap12",
    slug: "shock-mount-kit",
    image: "/product/images/shock-mount-kit.jpg",
    name: "Strut Mount Kit",
    category: "brakes-suspension",
    sku: "BRK-STM-072",
    basePrice: 1200,
    tierPricing: tiers(1200),
    moq: 12,
    packSizes: ["Single", "Pair"],
    grades: ["OEM", "Aftermarket"],
    description: "Bearing plate and mount in one kit, eliminates knocking noise on full steering lock.",
  },
  {
    id: "ap13",
    slug: "car-battery-60ah",
    image: "/product/images/car-battery-60ah.jpg",
    name: "Car Battery, 60Ah",
    category: "electrical-lighting",
    sku: "ELC-BAT-011",
    basePrice: 8500,
    tierPricing: tiers(8500),
    moq: 4,
    packSizes: ["Single"],
    grades: ["Standard", "AGM (Start-Stop)"],
    description: "Maintenance-free lead-acid battery, 540A cold-cranking. Fits most compact and mid-size sedans.",
    tag: "Bestseller",
  },
  {
    id: "ap14",
    slug: "led-headlight-bulb",
    image: "/product/images/led-headlight-bulb.jpg",
    name: "LED Headlight Bulb Set",
    category: "electrical-lighting",
    sku: "ELC-LED-019",
    basePrice: 1900,
    tierPricing: tiers(1900),
    moq: 12,
    packSizes: ["Pair", "Case of 10 pairs"],
    grades: ["6000K White", "3000K Warm"],
    description: "Plug-and-play LED conversion, 6000K daylight output, built-in cooling fan for long service life.",
    tag: "New",
  },
  {
    id: "ap15",
    slug: "alternator-remanufactured",
    image: "/product/images/alternator-remanufactured.jpg",
    name: "Alternator, Remanufactured",
    category: "electrical-lighting",
    sku: "ELC-ALT-004",
    basePrice: 9200,
    tierPricing: tiers(9200),
    moq: 3,
    packSizes: ["Single"],
    grades: ["Remanufactured OEM", "New Aftermarket"],
    description: "Tested to OE output spec, includes pulley. Common fitment across several 4-cylinder platforms.",
    tag: "Restocked",
  },
  {
    id: "ap16",
    slug: "oxygen-sensor",
    image: "/product/images/oxygen-sensor.jpg",
    name: "Oxygen (O2) Sensor",
    category: "electrical-lighting",
    sku: "ELC-O2S-026",
    basePrice: 1600,
    tierPricing: tiers(1600),
    moq: 12,
    packSizes: ["Single", "Pack of 6"],
    grades: ["OEM", "Aftermarket"],
    description: "Direct-fit upstream/downstream sensor, resolves check-engine lean/rich fault codes.",
  },
  {
    id: "ap17",
    slug: "abs-wheel-speed-sensor",
    image: "/product/images/abs-wheel-speed-sensor.jpeg",
    name: "ABS Wheel Speed Sensor",
    category: "electrical-lighting",
    sku: "ELC-ABS-033",
    basePrice: 1350,
    tierPricing: tiers(1350),
    moq: 12,
    packSizes: ["Single", "Pack of 4"],
    grades: ["OEM", "Aftermarket"],
    description: "Restores ABS/traction-control function. Includes connector pigtail, no splicing required.",
    tag: "New",
  },
  {
    id: "ap18",
    slug: "fog-light-assembly",
    image: "/product/images/fog-light-assembly.jpg",
    name: "Fog Light Assembly",
    category: "electrical-lighting",
    sku: "ELC-FOG-008",
    basePrice: 2400,
    tierPricing: tiers(2400),
    moq: 12,
    packSizes: ["Pair", "Case of 6 pairs"],
    grades: ["OEM Style", "Smoked Lens"],
    description: "Direct bolt-in housing with bulb included. Matches OE beam pattern and mounting points.",
  },
];

export function autoPartsByCategory(category: AutoPartCategory): AutoPart[] {
  return autoParts.filter((p) => p.category === category);
}

export function getAutoPart(slug: string): AutoPart | undefined {
  return autoParts.find((p) => p.slug === slug);
}

export type { TierPrice };
